# Generated by Django 4.0.2 on 2022-02-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_house_electricity_house_water'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='water_availability',
            field=models.CharField(blank=True, choices=[('24hrs', '24hrs'), ('Pomed once per day', 'Pomed once per day')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='water',
            field=models.CharField(blank=True, choices=[('Well', 'Well'), ('Borehole', 'Borehole')], max_length=10, null=True),
        ),
    ]
