# Generated by Django 4.0.2 on 2022-02-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_house_date_created_house_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='security',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
    ]
