# Generated by Django 4.0.2 on 2022-02-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_house_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='bathroom',
            field=models.CharField(blank=True, choices=[('Inside', 'Inside'), ('Outside', 'Outside')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='party',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
