# Generated by Django 4.0.2 on 2022-02-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_house_bathroom_house_party_house_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='smoking',
            field=models.CharField(blank=True, choices=[('Allowed', 'Allowed'), ('Not Allowed', 'Not Allowed')], max_length=20, null=True),
        ),
    ]
